name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0 - without v prefix)'
        required: true
        type: string

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Update version in Cargo.toml
        run: |
          sed -i 's/^version = ".*"/version = "${{ github.event.inputs.version }}"/' src-tauri/Cargo.toml
          
      - name: Update version in tauri.conf.json
        run: |
          sed -i 's/"version": ".*"/"version": "${{ github.event.inputs.version }}"/' src-tauri/tauri.conf.json
          
      - name: Create Release
        id: create-release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${{ github.event.inputs.version }}`,
              name: `CCUsage macOS Menubar v${{ github.event.inputs.version }}`,
              draft: true,
              prerelease: false,
              body: `## What's Changed

            <!-- Update this section with actual changes -->

            ## Installation

            ### macOS
            1. Download the \`.dmg\` file
            2. Open the DMG and drag the app to your Applications folder
            3. The app requires Node.js to be installed for ccusage functionality
            
            **Compatibility**: Apple Silicon (M1/M2/M3) Macs only

            ### Requirements
            - macOS 10.15 or later
            - Node.js (for ccusage CLI functionality)

            **Important: First-time setup for unsigned app**
            
            If you see "ccusage-macos-menubar.app is damaged and can't be opened":
            
            1. Open Terminal
            2. Run this command:
               \`\`\`bash
               xattr -cr /Applications/ccusage-macos-menubar.app
               \`\`\`
            3. The app should now open normally
            
            Alternative method:
            - Right-click the app and select "Open"
            - Click "Open" in the dialog that appears
            
            This only needs to be done once. The app is not actually damaged - macOS shows this message for unsigned apps downloaded from the internet.`
            });
            return data.id;

  build-tauri:
    needs: create-release
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update version in Cargo.toml
        run: |
          sed -i '' 's/^version = ".*"/version = "${{ github.event.inputs.version }}"/' src-tauri/Cargo.toml
          
      - name: Update version in tauri.conf.json  
        run: |
          sed -i '' 's/"version": ".*"/"version": "${{ github.event.inputs.version }}"/' src-tauri/tauri.conf.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Install dependencies
        run: yarn install

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          args: --target aarch64-apple-darwin